BEGIN TRANSACTION;
DROP TABLE IF EXISTS trains;
DROP TABLE IF EXISTS employees;
CREATE TABLE trains(
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
year INTEGER NOT NULL,
maker TEXT NOT NULL
);
INSERT INTO TRAINS VALUES(1,'Thomas the Tank Engine',1945,'Rev.W.Awdry');
INSERT INTO TRAINS VALUES(2,'Edward the Blue Engine',1943,'Rev.W.Awdry');
INSERT INTO TRAINS VALUES(3,'James the Red Engine',1946,'Rev.W.Awdry');
COMMIT;

CREATE TABLE employees(
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
train_id INTEGER NOT NULL,

FOREIGN_KEY(train_id) REFERENCES train(id)
);
INSERT INTO EMPLOYEES VALUES(1,'L.B.Billinton',1);
INSERT INTO EMPLOYEES VALUES(2,'W.F.Pettigrew',2);
INSERT INTO EMPLOYEES VALUES(3,'George Hughes',3);
BEGIN TRANSACTION;
COMMIT;
