require_relative '../models/app_record/act_rec'
require_relative '../models/employee'
require 'rack'
require_relative './tracks_controller'
require_relative './app_controller/router'
require_relative './app_controller/static'
