require_relative '../models/app_record/act_rec'
require_relative '../models/employee'
require 'rack'
require_relative './employees_controller'
require_relative './trains_controller'
require_relative './app_controller/router'
